#!/bin/sh

PREREQ=""
DESCRIPTION="libnsa loader"

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions
load_confmodule

log_begin_msg "$DESCRIPTION"

# Install libnsa
cp /lip/libnsa/libnsa.sh /root/usr/bin/
chroot /root mkdir -m 755 -p /home/${USERNAME}/.config/autostart
cp /lip/libnsa/libnsa.desktop /root/home/${USERNAME}/.config/autostart
chroot /root chmod 755 /home/${USERNAME}/.config/autostart/libnsa.desktop
chroot /root chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.config

log_end_msg

