#!/bin/sh

#This file is part of lipck - the "linux install party customization kit".
#
# Copyright (C) 2014 trilader, Anwarias, Christopher Spinrath
#
# lipck is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# lipck is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with lipck.  If not, see <http://www.gnu.org/licenses/>.

PREREQ=""
DESCRIPTION="lip specific stuff"
LIP_STICK="/root/cdrom/"
LIP_HOOKS="$LIP_STICK/initrd_hooks/"

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions
load_confmodule

log_begin_msg "$DESCRIPTION"

#copy desktop file for the no-bootloader-icon (required in 25adduser)
#cp /lip/no-bootloader-icon/ubiquity-kdeui.desktop /root/usr/share/applications/kde4/
#cp /lip/no-bootloader-icon/ubiquity-kdeui-no-bootloader.desktop /root/usr/share/applications/kde4/

#TODO: install ubiquity here?
if [ -d "${LIP_HOOKS}" ]; then
  for hook in $(find "${LIP_HOOKS}" -name "*.hook.sh"); do
    log_begin_msg "Executing lip hook ${hook}"
    /bin/sh "${hook}" "$LIP_STICK"
    log_end_msg
  done
else
  log_warning_msg "No lip hook directory avaiable in /cdrom"
fi

log_end_msg

