#!/bin/sh

PREREQ=""
DESCRIPTION="lip specific stuff"
LIP_HOOKS="/cdrom/initrd_hooks/"

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions
load_confmodule

log_begin_msg "$DESCRIPTION"

#copy desktop file for the no-bootloader-icon (required in 25adduser)
#cp /lip/no-bootloader-icon/ubiquity-kdeui.desktop /root/usr/share/applications/kde4/
#cp /lip/no-bootloader-icon/ubiquity-kdeui-no-bootloader.desktop /root/usr/share/applications/kde4/

#TODO: install ubiquity here?
for hook in $(find "${LIP_HOOKS}" -name "*.hook.sh"); do
  log_begin_msg "Executing lip hook ${hook}"
  /bin/sh "${hook}"
  log_end_msg
done

log_end_msg

